apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: nginx-demo
        track: canary
        version: "2.0.0"
    spec:
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: nginx-v2-config