apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
      version: "1.0.0"
  template:
    metadata:
      labels:
        app: nginx-demo
        track: stable
        version: "1.0.0"
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.5
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: nginx-v1-config