apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v1-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <body>
        <div class="container">
          <h1>Bem-vindo ao Kubernetes Demo!</h1>
          <div class="version">Versao 1.0.0 (Blue)</div>
        </div>
      </body>
    </html>