kind: Service
apiVersion: v1
metadata:
  name: nginx-app
spec:
  selector:
    app: nginx-demo
    version: "2.0.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer